
project:
  type: website
  output-dir: _site
  preview:
    browser: true

website:
  title: "ECO 230 — Section 12"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus/syllabus.qmd
      - text: "Slides"
        menu:
          - text: "Week 1"
            file: week01/week_01.qmd
          - text: "Week 2"
            file: week02/week_02.qmd
          - text: "Week 3"
            file: week03/week_03.qmd
          - text: "Week 4"
            file: week04/week_04.qmd
          - text: "Week 5"
            file: week05/week_05.qmd
          - text: "Week 6"
            file: week06/week_06.qmd
          - text: "Week 7"
            file: week07/week_07.qmd
      - text: "Homework"
        menu:
          - text: "Homework 1"
            file: week01/Homework_01.qmd
          - text: "Homework 2"
            file: week02/Homework_02.qmd
          - text: "Homework 3"
            file: week03/Homework_03.qmd
          - text: "Homework 4"
            file: week04/Homework_04.qmd
          - text: "Homework 5"
            file: week06/Homework_05.qmd
          - text: "Homework 6"
            file: week07/Homework_06.qmd
      - text: "Project 1"
        menu:
          - text: "Project Prompt"
            file: syllabus/project_1_prompt.qmd
          - text: "Project Timeline"
            file: syllabus/project_1_timeline.qmd

format:
  html:
    toc: false            # default for normal pages (we'll turn on ToC in syllabus.qmd only)
    number-sections: false
    css: styles/accessibility.css

execute:
  echo: false
  warning: false

editor: visual
