COPY (SELECT * FROM curated.orders ORDER BY purchased_at, order_key) TO '{{OUTPUT_ORDERS}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
COPY (SELECT * FROM curated.order_items ORDER BY order_key, order_item_number) TO '{{OUTPUT_ORDER_ITEMS}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
COPY (SELECT * FROM curated.payments ORDER BY order_key, payment_sequence) TO '{{OUTPUT_PAYMENTS}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
COPY (SELECT * FROM curated.reviews ORDER BY order_key) TO '{{OUTPUT_REVIEWS}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
COPY (SELECT * FROM curated.products ORDER BY product_key) TO '{{OUTPUT_PRODUCTS}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
COPY (SELECT * FROM curated.sellers ORDER BY seller_key) TO '{{OUTPUT_SELLERS}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
COPY (SELECT * FROM curated.marketing_leads ORDER BY first_contact_date, lead_key) TO '{{OUTPUT_MARKETING_LEADS}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
COPY (SELECT * FROM curated.order_analysis ORDER BY purchased_at, order_key) TO '{{OUTPUT_ORDER_ANALYSIS}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
