COPY (SELECT * FROM curated.patients ORDER BY patient_key)
TO '{{OUTPUT_PATIENTS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.encounters ORDER BY encounter_key)
TO '{{OUTPUT_ENCOUNTERS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.appointments ORDER BY appointment_key)
TO '{{OUTPUT_APPOINTMENTS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.satisfaction_surveys ORDER BY survey_key)
TO '{{OUTPUT_SATISFACTION_SURVEYS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.diagnoses ORDER BY diagnosis_key)
TO '{{OUTPUT_DIAGNOSES}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.procedures ORDER BY procedure_key)
TO '{{OUTPUT_PROCEDURES}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.medications ORDER BY medication_key)
TO '{{OUTPUT_MEDICATIONS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.observations ORDER BY observation_key)
TO '{{OUTPUT_OBSERVATIONS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.allergies ORDER BY allergy_key)
TO '{{OUTPUT_ALLERGIES}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.immunizations ORDER BY immunization_key)
TO '{{OUTPUT_IMMUNIZATIONS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.careplans ORDER BY careplan_key)
TO '{{OUTPUT_CAREPLANS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.claims ORDER BY claim_key)
TO '{{OUTPUT_CLAIMS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.claim_transactions ORDER BY claim_transaction_key)
TO '{{OUTPUT_CLAIM_TRANSACTIONS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.coverage_periods ORDER BY coverage_period_key)
TO '{{OUTPUT_COVERAGE_PERIODS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.organizations ORDER BY organization_key)
TO '{{OUTPUT_ORGANIZATIONS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.providers ORDER BY provider_key)
TO '{{OUTPUT_PROVIDERS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.payers ORDER BY payer_key)
TO '{{OUTPUT_PAYERS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
COPY (SELECT * FROM curated.encounter_analysis ORDER BY encounter_key)
TO '{{OUTPUT_ENCOUNTER_ANALYSIS}}' (FORMAT PARQUET, COMPRESSION ZSTD);
