COPY (
  SELECT * FROM curated.zip_geography ORDER BY zip5
) TO '{{OUTPUT_ZIP_GEOGRAPHY}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);

COPY (
  SELECT * FROM curated.zip_context ORDER BY zip5
) TO '{{OUTPUT_ZIP_CONTEXT}}' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
